// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"
	dto "manabu-service/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockIUserService is an autogenerated mock type for the IUserService type
type MockIUserService struct {
	mock.Mock
}

type MockIUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserService) EXPECT() *MockIUserService_Expecter {
	return &MockIUserService_Expecter{mock: &_m.Mock}
}

// GetUserByUUID provides a mock function with given fields: _a0, _a1
func (_m *MockIUserService) GetUserByUUID(_a0 context.Context, _a1 string) (*dto.UserResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUUID")
	}

	var r0 *dto.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.UserResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.UserResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_GetUserByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUUID'
type MockIUserService_GetUserByUUID_Call struct {
	*mock.Call
}

// GetUserByUUID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIUserService_Expecter) GetUserByUUID(_a0 interface{}, _a1 interface{}) *MockIUserService_GetUserByUUID_Call {
	return &MockIUserService_GetUserByUUID_Call{Call: _e.mock.On("GetUserByUUID", _a0, _a1)}
}

func (_c *MockIUserService_GetUserByUUID_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIUserService_GetUserByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIUserService_GetUserByUUID_Call) Return(_a0 *dto.UserResponse, _a1 error) *MockIUserService_GetUserByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_GetUserByUUID_Call) RunAndReturn(run func(context.Context, string) (*dto.UserResponse, error)) *MockIUserService_GetUserByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserLogin provides a mock function with given fields: _a0
func (_m *MockIUserService) GetUserLogin(_a0 context.Context) (*dto.UserResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLogin")
	}

	var r0 *dto.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*dto.UserResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *dto.UserResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_GetUserLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserLogin'
type MockIUserService_GetUserLogin_Call struct {
	*mock.Call
}

// GetUserLogin is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockIUserService_Expecter) GetUserLogin(_a0 interface{}) *MockIUserService_GetUserLogin_Call {
	return &MockIUserService_GetUserLogin_Call{Call: _e.mock.On("GetUserLogin", _a0)}
}

func (_c *MockIUserService_GetUserLogin_Call) Run(run func(_a0 context.Context)) *MockIUserService_GetUserLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIUserService_GetUserLogin_Call) Return(_a0 *dto.UserResponse, _a1 error) *MockIUserService_GetUserLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_GetUserLogin_Call) RunAndReturn(run func(context.Context) (*dto.UserResponse, error)) *MockIUserService_GetUserLogin_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: _a0, _a1
func (_m *MockIUserService) Login(_a0 context.Context, _a1 *dto.LoginRequest) (*dto.LoginResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.LoginRequest) (*dto.LoginResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.LoginRequest) *dto.LoginResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.LoginRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockIUserService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *dto.LoginRequest
func (_e *MockIUserService_Expecter) Login(_a0 interface{}, _a1 interface{}) *MockIUserService_Login_Call {
	return &MockIUserService_Login_Call{Call: _e.mock.On("Login", _a0, _a1)}
}

func (_c *MockIUserService_Login_Call) Run(run func(_a0 context.Context, _a1 *dto.LoginRequest)) *MockIUserService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.LoginRequest))
	})
	return _c
}

func (_c *MockIUserService_Login_Call) Return(_a0 *dto.LoginResponse, _a1 error) *MockIUserService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_Login_Call) RunAndReturn(run func(context.Context, *dto.LoginRequest) (*dto.LoginResponse, error)) *MockIUserService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *MockIUserService) Register(_a0 context.Context, _a1 *dto.RegisterRequest) (*dto.RegisterResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *dto.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RegisterRequest) (*dto.RegisterResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RegisterRequest) *dto.RegisterResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.RegisterRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockIUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *dto.RegisterRequest
func (_e *MockIUserService_Expecter) Register(_a0 interface{}, _a1 interface{}) *MockIUserService_Register_Call {
	return &MockIUserService_Register_Call{Call: _e.mock.On("Register", _a0, _a1)}
}

func (_c *MockIUserService_Register_Call) Run(run func(_a0 context.Context, _a1 *dto.RegisterRequest)) *MockIUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.RegisterRequest))
	})
	return _c
}

func (_c *MockIUserService_Register_Call) Return(_a0 *dto.RegisterResponse, _a1 error) *MockIUserService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_Register_Call) RunAndReturn(run func(context.Context, *dto.RegisterRequest) (*dto.RegisterResponse, error)) *MockIUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockIUserService) Update(_a0 context.Context, _a1 *dto.UpdateRequest, _a2 string) (*dto.UserResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *dto.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateRequest, string) (*dto.UserResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateRequest, string) *dto.UserResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.UpdateRequest, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIUserService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *dto.UpdateRequest
//   - _a2 string
func (_e *MockIUserService_Expecter) Update(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockIUserService_Update_Call {
	return &MockIUserService_Update_Call{Call: _e.mock.On("Update", _a0, _a1, _a2)}
}

func (_c *MockIUserService_Update_Call) Run(run func(_a0 context.Context, _a1 *dto.UpdateRequest, _a2 string)) *MockIUserService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.UpdateRequest), args[2].(string))
	})
	return _c
}

func (_c *MockIUserService_Update_Call) Return(_a0 *dto.UserResponse, _a1 error) *MockIUserService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_Update_Call) RunAndReturn(run func(context.Context, *dto.UpdateRequest, string) (*dto.UserResponse, error)) *MockIUserService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUserService creates a new instance of MockIUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserService {
	mock := &MockIUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
