// Code generated by mockery v2.53.5. DO NOT EDIT.

package repositories

import (
	context "context"
	dto "manabu-service/domain/dto"

	mock "github.com/stretchr/testify/mock"

	models "manabu-service/domain/models"
)

// MockIUserRepository is an autogenerated mock type for the IUserRepository type
type MockIUserRepository struct {
	mock.Mock
}

type MockIUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserRepository) EXPECT() *MockIUserRepository_Expecter {
	return &MockIUserRepository_Expecter{mock: &_m.Mock}
}

// FindByEmail provides a mock function with given fields: _a0, _a1
func (_m *MockIUserRepository) FindByEmail(_a0 context.Context, _a1 string) (*models.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockIUserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIUserRepository_Expecter) FindByEmail(_a0 interface{}, _a1 interface{}) *MockIUserRepository_FindByEmail_Call {
	return &MockIUserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", _a0, _a1)}
}

func (_c *MockIUserRepository_FindByEmail_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIUserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIUserRepository_FindByEmail_Call) Return(_a0 *models.User, _a1 error) *MockIUserRepository_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_FindByEmail_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockIUserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUUID provides a mock function with given fields: _a0, _a1
func (_m *MockIUserRepository) FindByUUID(_a0 context.Context, _a1 string) (*models.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindByUUID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_FindByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUUID'
type MockIUserRepository_FindByUUID_Call struct {
	*mock.Call
}

// FindByUUID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIUserRepository_Expecter) FindByUUID(_a0 interface{}, _a1 interface{}) *MockIUserRepository_FindByUUID_Call {
	return &MockIUserRepository_FindByUUID_Call{Call: _e.mock.On("FindByUUID", _a0, _a1)}
}

func (_c *MockIUserRepository_FindByUUID_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIUserRepository_FindByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIUserRepository_FindByUUID_Call) Return(_a0 *models.User, _a1 error) *MockIUserRepository_FindByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_FindByUUID_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockIUserRepository_FindByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function with given fields: _a0, _a1
func (_m *MockIUserRepository) FindByUsername(_a0 context.Context, _a1 string) (*models.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockIUserRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockIUserRepository_Expecter) FindByUsername(_a0 interface{}, _a1 interface{}) *MockIUserRepository_FindByUsername_Call {
	return &MockIUserRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", _a0, _a1)}
}

func (_c *MockIUserRepository_FindByUsername_Call) Run(run func(_a0 context.Context, _a1 string)) *MockIUserRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIUserRepository_FindByUsername_Call) Return(_a0 *models.User, _a1 error) *MockIUserRepository_FindByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_FindByUsername_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockIUserRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *MockIUserRepository) Register(_a0 context.Context, _a1 *dto.RegisterRequest) (*models.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RegisterRequest) (*models.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RegisterRequest) *models.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.RegisterRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockIUserRepository_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *dto.RegisterRequest
func (_e *MockIUserRepository_Expecter) Register(_a0 interface{}, _a1 interface{}) *MockIUserRepository_Register_Call {
	return &MockIUserRepository_Register_Call{Call: _e.mock.On("Register", _a0, _a1)}
}

func (_c *MockIUserRepository_Register_Call) Run(run func(_a0 context.Context, _a1 *dto.RegisterRequest)) *MockIUserRepository_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.RegisterRequest))
	})
	return _c
}

func (_c *MockIUserRepository_Register_Call) Return(_a0 *models.User, _a1 error) *MockIUserRepository_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_Register_Call) RunAndReturn(run func(context.Context, *dto.RegisterRequest) (*models.User, error)) *MockIUserRepository_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockIUserRepository) Update(_a0 context.Context, _a1 *dto.UpdateRequest, _a2 string) (*models.User, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateRequest, string) (*models.User, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateRequest, string) *models.User); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.UpdateRequest, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *dto.UpdateRequest
//   - _a2 string
func (_e *MockIUserRepository_Expecter) Update(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockIUserRepository_Update_Call {
	return &MockIUserRepository_Update_Call{Call: _e.mock.On("Update", _a0, _a1, _a2)}
}

func (_c *MockIUserRepository_Update_Call) Run(run func(_a0 context.Context, _a1 *dto.UpdateRequest, _a2 string)) *MockIUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.UpdateRequest), args[2].(string))
	})
	return _c
}

func (_c *MockIUserRepository_Update_Call) Return(_a0 *models.User, _a1 error) *MockIUserRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_Update_Call) RunAndReturn(run func(context.Context, *dto.UpdateRequest, string) (*models.User, error)) *MockIUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUserRepository creates a new instance of MockIUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserRepository {
	mock := &MockIUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
