// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	jlpt_level "manabu-service/services/jlpt_level"

	mock "github.com/stretchr/testify/mock"

	services "manabu-service/services/category"

	tag "manabu-service/services/tag"

	user "manabu-service/services/user"

	user_vocabulary_status "manabu-service/services/user_vocabulary_status"

	vocabulary "manabu-service/services/vocabulary"
)

// MockIServiceRegistry is an autogenerated mock type for the IServiceRegistry type
type MockIServiceRegistry struct {
	mock.Mock
}

type MockIServiceRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIServiceRegistry) EXPECT() *MockIServiceRegistry_Expecter {
	return &MockIServiceRegistry_Expecter{mock: &_m.Mock}
}

// GetCategory provides a mock function with no fields
func (_m *MockIServiceRegistry) GetCategory() services.ICategoryService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCategory")
	}

	var r0 services.ICategoryService
	if rf, ok := ret.Get(0).(func() services.ICategoryService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(services.ICategoryService)
		}
	}

	return r0
}

// MockIServiceRegistry_GetCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategory'
type MockIServiceRegistry_GetCategory_Call struct {
	*mock.Call
}

// GetCategory is a helper method to define mock.On call
func (_e *MockIServiceRegistry_Expecter) GetCategory() *MockIServiceRegistry_GetCategory_Call {
	return &MockIServiceRegistry_GetCategory_Call{Call: _e.mock.On("GetCategory")}
}

func (_c *MockIServiceRegistry_GetCategory_Call) Run(run func()) *MockIServiceRegistry_GetCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIServiceRegistry_GetCategory_Call) Return(_a0 services.ICategoryService) *MockIServiceRegistry_GetCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIServiceRegistry_GetCategory_Call) RunAndReturn(run func() services.ICategoryService) *MockIServiceRegistry_GetCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetJlptLevel provides a mock function with no fields
func (_m *MockIServiceRegistry) GetJlptLevel() jlpt_level.IJlptLevelService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetJlptLevel")
	}

	var r0 jlpt_level.IJlptLevelService
	if rf, ok := ret.Get(0).(func() jlpt_level.IJlptLevelService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jlpt_level.IJlptLevelService)
		}
	}

	return r0
}

// MockIServiceRegistry_GetJlptLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJlptLevel'
type MockIServiceRegistry_GetJlptLevel_Call struct {
	*mock.Call
}

// GetJlptLevel is a helper method to define mock.On call
func (_e *MockIServiceRegistry_Expecter) GetJlptLevel() *MockIServiceRegistry_GetJlptLevel_Call {
	return &MockIServiceRegistry_GetJlptLevel_Call{Call: _e.mock.On("GetJlptLevel")}
}

func (_c *MockIServiceRegistry_GetJlptLevel_Call) Run(run func()) *MockIServiceRegistry_GetJlptLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIServiceRegistry_GetJlptLevel_Call) Return(_a0 jlpt_level.IJlptLevelService) *MockIServiceRegistry_GetJlptLevel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIServiceRegistry_GetJlptLevel_Call) RunAndReturn(run func() jlpt_level.IJlptLevelService) *MockIServiceRegistry_GetJlptLevel_Call {
	_c.Call.Return(run)
	return _c
}

// GetTag provides a mock function with no fields
func (_m *MockIServiceRegistry) GetTag() tag.ITagService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTag")
	}

	var r0 tag.ITagService
	if rf, ok := ret.Get(0).(func() tag.ITagService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tag.ITagService)
		}
	}

	return r0
}

// MockIServiceRegistry_GetTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTag'
type MockIServiceRegistry_GetTag_Call struct {
	*mock.Call
}

// GetTag is a helper method to define mock.On call
func (_e *MockIServiceRegistry_Expecter) GetTag() *MockIServiceRegistry_GetTag_Call {
	return &MockIServiceRegistry_GetTag_Call{Call: _e.mock.On("GetTag")}
}

func (_c *MockIServiceRegistry_GetTag_Call) Run(run func()) *MockIServiceRegistry_GetTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIServiceRegistry_GetTag_Call) Return(_a0 tag.ITagService) *MockIServiceRegistry_GetTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIServiceRegistry_GetTag_Call) RunAndReturn(run func() tag.ITagService) *MockIServiceRegistry_GetTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with no fields
func (_m *MockIServiceRegistry) GetUser() user.IUserService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 user.IUserService
	if rf, ok := ret.Get(0).(func() user.IUserService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(user.IUserService)
		}
	}

	return r0
}

// MockIServiceRegistry_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockIServiceRegistry_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
func (_e *MockIServiceRegistry_Expecter) GetUser() *MockIServiceRegistry_GetUser_Call {
	return &MockIServiceRegistry_GetUser_Call{Call: _e.mock.On("GetUser")}
}

func (_c *MockIServiceRegistry_GetUser_Call) Run(run func()) *MockIServiceRegistry_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIServiceRegistry_GetUser_Call) Return(_a0 user.IUserService) *MockIServiceRegistry_GetUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIServiceRegistry_GetUser_Call) RunAndReturn(run func() user.IUserService) *MockIServiceRegistry_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserVocabularyStatus provides a mock function with no fields
func (_m *MockIServiceRegistry) GetUserVocabularyStatus() user_vocabulary_status.IUserVocabularyStatusService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserVocabularyStatus")
	}

	var r0 user_vocabulary_status.IUserVocabularyStatusService
	if rf, ok := ret.Get(0).(func() user_vocabulary_status.IUserVocabularyStatusService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(user_vocabulary_status.IUserVocabularyStatusService)
		}
	}

	return r0
}

// MockIServiceRegistry_GetUserVocabularyStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserVocabularyStatus'
type MockIServiceRegistry_GetUserVocabularyStatus_Call struct {
	*mock.Call
}

// GetUserVocabularyStatus is a helper method to define mock.On call
func (_e *MockIServiceRegistry_Expecter) GetUserVocabularyStatus() *MockIServiceRegistry_GetUserVocabularyStatus_Call {
	return &MockIServiceRegistry_GetUserVocabularyStatus_Call{Call: _e.mock.On("GetUserVocabularyStatus")}
}

func (_c *MockIServiceRegistry_GetUserVocabularyStatus_Call) Run(run func()) *MockIServiceRegistry_GetUserVocabularyStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIServiceRegistry_GetUserVocabularyStatus_Call) Return(_a0 user_vocabulary_status.IUserVocabularyStatusService) *MockIServiceRegistry_GetUserVocabularyStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIServiceRegistry_GetUserVocabularyStatus_Call) RunAndReturn(run func() user_vocabulary_status.IUserVocabularyStatusService) *MockIServiceRegistry_GetUserVocabularyStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetVocabulary provides a mock function with no fields
func (_m *MockIServiceRegistry) GetVocabulary() vocabulary.IVocabularyService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVocabulary")
	}

	var r0 vocabulary.IVocabularyService
	if rf, ok := ret.Get(0).(func() vocabulary.IVocabularyService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vocabulary.IVocabularyService)
		}
	}

	return r0
}

// MockIServiceRegistry_GetVocabulary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVocabulary'
type MockIServiceRegistry_GetVocabulary_Call struct {
	*mock.Call
}

// GetVocabulary is a helper method to define mock.On call
func (_e *MockIServiceRegistry_Expecter) GetVocabulary() *MockIServiceRegistry_GetVocabulary_Call {
	return &MockIServiceRegistry_GetVocabulary_Call{Call: _e.mock.On("GetVocabulary")}
}

func (_c *MockIServiceRegistry_GetVocabulary_Call) Run(run func()) *MockIServiceRegistry_GetVocabulary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIServiceRegistry_GetVocabulary_Call) Return(_a0 vocabulary.IVocabularyService) *MockIServiceRegistry_GetVocabulary_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIServiceRegistry_GetVocabulary_Call) RunAndReturn(run func() vocabulary.IVocabularyService) *MockIServiceRegistry_GetVocabulary_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIServiceRegistry creates a new instance of MockIServiceRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIServiceRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIServiceRegistry {
	mock := &MockIServiceRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
