// Code generated by mockery v2.53.5. DO NOT EDIT.

package repositories

import (
	jlpt_level "manabu-service/repositories/jlpt_level"

	mock "github.com/stretchr/testify/mock"

	repositories "manabu-service/repositories/category"

	tag "manabu-service/repositories/tag"

	user "manabu-service/repositories/user"

	vocabulary "manabu-service/repositories/vocabulary"
)

// MockIRepositoryRegistry is an autogenerated mock type for the IRepositoryRegistry type
type MockIRepositoryRegistry struct {
	mock.Mock
}

type MockIRepositoryRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepositoryRegistry) EXPECT() *MockIRepositoryRegistry_Expecter {
	return &MockIRepositoryRegistry_Expecter{mock: &_m.Mock}
}

// GetCategory provides a mock function with no fields
func (_m *MockIRepositoryRegistry) GetCategory() repositories.ICategoryRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCategory")
	}

	var r0 repositories.ICategoryRepository
	if rf, ok := ret.Get(0).(func() repositories.ICategoryRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.ICategoryRepository)
		}
	}

	return r0
}

// MockIRepositoryRegistry_GetCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategory'
type MockIRepositoryRegistry_GetCategory_Call struct {
	*mock.Call
}

// GetCategory is a helper method to define mock.On call
func (_e *MockIRepositoryRegistry_Expecter) GetCategory() *MockIRepositoryRegistry_GetCategory_Call {
	return &MockIRepositoryRegistry_GetCategory_Call{Call: _e.mock.On("GetCategory")}
}

func (_c *MockIRepositoryRegistry_GetCategory_Call) Run(run func()) *MockIRepositoryRegistry_GetCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRepositoryRegistry_GetCategory_Call) Return(_a0 repositories.ICategoryRepository) *MockIRepositoryRegistry_GetCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepositoryRegistry_GetCategory_Call) RunAndReturn(run func() repositories.ICategoryRepository) *MockIRepositoryRegistry_GetCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetJlptLevel provides a mock function with no fields
func (_m *MockIRepositoryRegistry) GetJlptLevel() jlpt_level.IJlptLevelRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetJlptLevel")
	}

	var r0 jlpt_level.IJlptLevelRepository
	if rf, ok := ret.Get(0).(func() jlpt_level.IJlptLevelRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jlpt_level.IJlptLevelRepository)
		}
	}

	return r0
}

// MockIRepositoryRegistry_GetJlptLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJlptLevel'
type MockIRepositoryRegistry_GetJlptLevel_Call struct {
	*mock.Call
}

// GetJlptLevel is a helper method to define mock.On call
func (_e *MockIRepositoryRegistry_Expecter) GetJlptLevel() *MockIRepositoryRegistry_GetJlptLevel_Call {
	return &MockIRepositoryRegistry_GetJlptLevel_Call{Call: _e.mock.On("GetJlptLevel")}
}

func (_c *MockIRepositoryRegistry_GetJlptLevel_Call) Run(run func()) *MockIRepositoryRegistry_GetJlptLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRepositoryRegistry_GetJlptLevel_Call) Return(_a0 jlpt_level.IJlptLevelRepository) *MockIRepositoryRegistry_GetJlptLevel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepositoryRegistry_GetJlptLevel_Call) RunAndReturn(run func() jlpt_level.IJlptLevelRepository) *MockIRepositoryRegistry_GetJlptLevel_Call {
	_c.Call.Return(run)
	return _c
}

// GetTag provides a mock function with no fields
func (_m *MockIRepositoryRegistry) GetTag() tag.ITagRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTag")
	}

	var r0 tag.ITagRepository
	if rf, ok := ret.Get(0).(func() tag.ITagRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tag.ITagRepository)
		}
	}

	return r0
}

// MockIRepositoryRegistry_GetTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTag'
type MockIRepositoryRegistry_GetTag_Call struct {
	*mock.Call
}

// GetTag is a helper method to define mock.On call
func (_e *MockIRepositoryRegistry_Expecter) GetTag() *MockIRepositoryRegistry_GetTag_Call {
	return &MockIRepositoryRegistry_GetTag_Call{Call: _e.mock.On("GetTag")}
}

func (_c *MockIRepositoryRegistry_GetTag_Call) Run(run func()) *MockIRepositoryRegistry_GetTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRepositoryRegistry_GetTag_Call) Return(_a0 tag.ITagRepository) *MockIRepositoryRegistry_GetTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepositoryRegistry_GetTag_Call) RunAndReturn(run func() tag.ITagRepository) *MockIRepositoryRegistry_GetTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with no fields
func (_m *MockIRepositoryRegistry) GetUser() user.IUserRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 user.IUserRepository
	if rf, ok := ret.Get(0).(func() user.IUserRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(user.IUserRepository)
		}
	}

	return r0
}

// MockIRepositoryRegistry_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockIRepositoryRegistry_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
func (_e *MockIRepositoryRegistry_Expecter) GetUser() *MockIRepositoryRegistry_GetUser_Call {
	return &MockIRepositoryRegistry_GetUser_Call{Call: _e.mock.On("GetUser")}
}

func (_c *MockIRepositoryRegistry_GetUser_Call) Run(run func()) *MockIRepositoryRegistry_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRepositoryRegistry_GetUser_Call) Return(_a0 user.IUserRepository) *MockIRepositoryRegistry_GetUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepositoryRegistry_GetUser_Call) RunAndReturn(run func() user.IUserRepository) *MockIRepositoryRegistry_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetVocabulary provides a mock function with no fields
func (_m *MockIRepositoryRegistry) GetVocabulary() vocabulary.IVocabularyRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVocabulary")
	}

	var r0 vocabulary.IVocabularyRepository
	if rf, ok := ret.Get(0).(func() vocabulary.IVocabularyRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vocabulary.IVocabularyRepository)
		}
	}

	return r0
}

// MockIRepositoryRegistry_GetVocabulary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVocabulary'
type MockIRepositoryRegistry_GetVocabulary_Call struct {
	*mock.Call
}

// GetVocabulary is a helper method to define mock.On call
func (_e *MockIRepositoryRegistry_Expecter) GetVocabulary() *MockIRepositoryRegistry_GetVocabulary_Call {
	return &MockIRepositoryRegistry_GetVocabulary_Call{Call: _e.mock.On("GetVocabulary")}
}

func (_c *MockIRepositoryRegistry_GetVocabulary_Call) Run(run func()) *MockIRepositoryRegistry_GetVocabulary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRepositoryRegistry_GetVocabulary_Call) Return(_a0 vocabulary.IVocabularyRepository) *MockIRepositoryRegistry_GetVocabulary_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepositoryRegistry_GetVocabulary_Call) RunAndReturn(run func() vocabulary.IVocabularyRepository) *MockIRepositoryRegistry_GetVocabulary_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRepositoryRegistry creates a new instance of MockIRepositoryRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepositoryRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepositoryRegistry {
	mock := &MockIRepositoryRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
